services:
  mysql:
    image: mysql:8.0
    container_name: btc_pipeline_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: btc_data
      MYSQL_USER: pipeline_user
      MYSQL_PASSWORD: pipeline_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  pipeline:
    build: .
    container_name: btc_pipeline
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: pipeline_user
      DB_PASSWORD: pipeline_pass
      DB_NAME: btc_data
    volumes:
      - ./raw_data:/app/raw_data
      - ./data:/app/data
    restart: on-failure
    # Remove command if you want to use Dockerfile default
    # command: python main.py pipeline

volumes:
  mysql_data:
